package toleco.view.gui;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 * Displays a summary of a battle between two units. Images of the two battling units,
 * their team names, and a description of the result of the battle are displayed.
 *
 * @author Matt Tognetti
 * @version 1.0
 */
public class BattleSummary extends javax.swing.JPanel
{

    /** 
     * Creates new form BattleSummary.
     */
    public BattleSummary()
    {
        initComponents();
    }


    /**
     * Displays a summary of a battle between two units. Displays images of the two units
     * and a text description of the results of the battle.
     * @param attacker an image of the attacking unit
     * @param defender an image of the defending unit
     * @param summary a description of what happened in the battle
     */
    public void setSummary(BufferedImage attacker, BufferedImage defender,
            String summary)
    {
        //SET attacker icon
        attackingUnit.setIcon(new ImageIcon(attacker));
        //SET defender icon
        defendingUnit.setIcon(new ImageIcon(defender));
        //SET summary text
        battleSummary.setText(summary);
    }

    //CHECKSTYLE:OFF - Ignore generated code.
    // Authorized by Dr. Dalbey.

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attackingUnit = new javax.swing.JLabel();
        defendingUnit = new javax.swing.JLabel();
        vs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        battleSummary = new javax.swing.JTextArea();
        attackerLabel = new javax.swing.JLabel();
        defenderLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(200, 300));

        attackingUnit.setMaximumSize(new java.awt.Dimension(40, 40));
        attackingUnit.setPreferredSize(new java.awt.Dimension(40, 40));

        defendingUnit.setPreferredSize(new java.awt.Dimension(40, 40));

        vs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs.setText("vs");
        vs.setPreferredSize(new java.awt.Dimension(44, 20));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(224, 79));

        battleSummary.setColumns(20);
        battleSummary.setEditable(false);
        battleSummary.setLineWrap(true);
        battleSummary.setRows(5);
        battleSummary.setWrapStyleWord(true);
        jScrollPane1.setViewportView(battleSummary);

        attackerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attackerLabel.setText("Attacker");

        defenderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defenderLabel.setText("Defender");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(attackerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(attackingUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(defendingUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(defenderLabel)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(attackingUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(attackerLabel)
                            .addComponent(defenderLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(defendingUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attackerLabel;
    private javax.swing.JLabel attackingUnit;
    private javax.swing.JTextArea battleSummary;
    private javax.swing.JLabel defenderLabel;
    private javax.swing.JLabel defendingUnit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel vs;
    // End of variables declaration//GEN-END:variables

    //CHECKSTYLE:OFF
}
