package toleco.view.gui;

/**
 * Displays a backstory panel in the StatusView.
 *
 * @author Matt Tognetti
 * @version 1.0
 */
public class BackStory extends javax.swing.JPanel
{

    /** 
     * Creates new form BackStory.
     */
    public BackStory()
    {
        initComponents();
    }

    /**
     * Displays a backstory for the current map.
     * @param backstory description or story for the current map
     */
    public void updateText(String backstory)
    {
        //SET the backstory text
        backStory.setText(backstory);
    }

    //CHECKSTYLE:OFF - Ignore generated code.
    // Authorized by Dr. Dalbey.
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        backStory = new javax.swing.JTextArea();
        toleco = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(200, 300));
        setRequestFocusEnabled(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(244, 79));

        backStory.setColumns(20);
        backStory.setEditable(false);
        backStory.setLineWrap(true);
        backStory.setRows(5);
        backStory.setWrapStyleWord(true);
        jScrollPane1.setViewportView(backStory);

        toleco.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        toleco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toleco.setText("Toleco");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toleco, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toleco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea backStory;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel toleco;
    // End of variables declaration//GEN-END:variables

    //CHECKSTYLE:ON
}
